// Blog posts for livingreen.life/blog — informative articles that answer real searches
// in the upholstery niche and link back to the service and city pages (SEO clusters).

export interface BlogBlock {
  type: 'p' | 'h2' | 'ul';
  text?: string;
  items?: string[];
}

export interface BlogPost {
  slug: string;
  title: string;
  metaTitle: string;
  excerpt: string;
  date: string; // ISO date — articles with a FUTURE date are queued and appear automatically once their date arrives (revealed by the weekly Vercel cron rebuild).
  image: string;
  readTime: string;
  keywords: string[];
  body: BlogBlock[];
}

// Only posts whose date has arrived are live. Future-dated posts are a publishing
// queue: the weekly Vercel cron rebuild reveals the next one automatically.
export function publishedPosts(): BlogPost[] {
  const today = new Date().toISOString().slice(0, 10);
  return BLOG_POSTS.filter((p) => p.date <= today).sort((a, b) => b.date.localeCompare(a.date));
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'upholstery-cleaning-salt-lake-city-guide',
    title: 'Upholstery & Couch Cleaning in Salt Lake City: A Local Guide',
    metaTitle: 'Upholstery & Couch Cleaning in Salt Lake City, UT | LivinGreen',
    excerpt: 'What Salt Lake City homeowners should know about keeping couches, sofas and sectionals fresh in our dry climate, plus local pricing.',
    date: '2026-06-24',
    image: '/images/gallery/gallery-13.jpg',
    readTime: '4 min read',
    keywords: ['upholstery cleaning salt lake city', 'couch cleaning salt lake city', 'sofa cleaning slc'],
    body: [
      { type: 'p', text: 'Salt Lake City living is hard on furniture. Between the dry desert air, the dust that blows in off the valley, and busy households with kids and pets, couches and sofas pick up more dirt than most people realize. If you are searching for upholstery cleaning in Salt Lake City, here is what is worth knowing.' },
      { type: 'h2', text: 'Why Salt Lake couches get dirty fast' },
      { type: 'p', text: 'Our climate is dry and dusty, so fine particles settle deep into upholstery fibers where a vacuum cannot reach. Over time this dulls the color and traps allergens. Homes near busy roads or with forced-air heating tend to see it even faster.' },
      { type: 'h2', text: 'What couch cleaning costs in Salt Lake City' },
      { type: 'p', text: 'Pricing is the same across the valley and based on the size of the piece:' },
      { type: 'ul', items: ['Single seat sofa: from $35', 'Loveseat: around $65', 'Three seat sofa: around $85', 'Sectionals: from $100', 'Add fabric protection to keep it cleaner longer'] },
      { type: 'h2', text: 'We come to you anywhere in the valley' },
      { type: 'p', text: 'LivinGreen brings everything to your door, from downtown and the Avenues to Sugar House, Holladay, Millcreek and the south end of the county. We use eco-friendly products and hot water extraction that dries fast, so your couch is usable again the same day.' },
      { type: 'p', text: 'Ready for a fresh couch? Get a free quote for upholstery cleaning in Salt Lake City and across Salt Lake County.' },
    ],
  },
  {
    slug: 'upholstery-cleaning-provo-orem-guide',
    title: 'Couch & Upholstery Cleaning in Provo and Orem',
    metaTitle: 'Couch & Upholstery Cleaning in Provo and Orem, UT | LivinGreen',
    excerpt: 'A practical guide for Provo and Orem families on cleaning sofas, sectionals and student-rental furniture, with local pricing and tips.',
    date: '2026-06-24',
    image: '/images/gallery/gallery-16.jpg',
    readTime: '4 min read',
    keywords: ['upholstery cleaning provo', 'couch cleaning orem', 'sofa cleaning provo orem'],
    body: [
      { type: 'p', text: 'Provo and Orem are full of busy households and student rentals, and that means a lot of well-used couches. Whether you are a family in north Orem or a landlord turning over a Provo apartment near campus, professional upholstery cleaning makes furniture look and smell new again.' },
      { type: 'h2', text: 'Great for rentals and turnovers' },
      { type: 'p', text: 'Landlords and property managers around BYU and UVU use us between tenants. A deep clean removes stains, odors and allergens from couches and mattresses left behind, which protects your furniture investment and helps units show better.' },
      { type: 'h2', text: 'Family homes in Utah County' },
      { type: 'p', text: 'For families, pet stains and food spills are the usual culprits. Our hot water extraction lifts them out at the source rather than just masking them, and our products are safe for kids and pets.' },
      { type: 'h2', text: 'Local pricing' },
      { type: 'ul', items: ['Single seat sofa: from $35', 'Loveseat: around $65', 'Three seat sofa: around $85', 'Sectionals: from $100', 'Dining chairs: $10 to $20 each'] },
      { type: 'p', text: 'We serve Provo, Orem and the surrounding Utah County cities. Get a free quote for couch and upholstery cleaning in Provo or Orem today.' },
    ],
  },
  {
    slug: 'upholstery-cleaning-lehi-silicon-slopes-guide',
    title: 'Upholstery Cleaning in Lehi and the Silicon Slopes Area',
    metaTitle: 'Upholstery & Couch Cleaning in Lehi, UT | LivinGreen',
    excerpt: 'For the fast-growing Lehi, American Fork and Saratoga Springs area: how to keep new furniture looking new, plus local service details.',
    date: '2026-06-24',
    image: '/images/gallery/gallery-20.jpg',
    readTime: '3 min read',
    keywords: ['upholstery cleaning lehi', 'couch cleaning lehi', 'sofa cleaning silicon slopes'],
    body: [
      { type: 'p', text: 'Lehi and the Silicon Slopes corridor are some of the fastest-growing communities in Utah, full of newer homes and nice furniture worth protecting. If you just moved in or want to keep a newer sofa looking its best, here is how upholstery cleaning helps.' },
      { type: 'h2', text: 'Protect newer furniture early' },
      { type: 'p', text: 'The best time to add fabric protection is when a couch is still new and clean. It creates an invisible barrier so spills bead up instead of soaking in, which is ideal for busy young families in Lehi, American Fork, Highland and Saratoga Springs.' },
      { type: 'h2', text: 'Already lived-in?' },
      { type: 'p', text: 'No problem. Our deep clean removes built-up dirt, pet hair and stains from sofas, sectionals and recliners, then we can protect the fabric so it stays fresh between cleanings.' },
      { type: 'h2', text: 'At-home service across north Utah County' },
      { type: 'p', text: 'We bring everything to your door, dry fast, and use eco-friendly products. Serving Lehi, American Fork, Highland, Alpine, Saratoga Springs and Eagle Mountain. Get a free quote for upholstery cleaning in Lehi today.' },
    ],
  },
  {
    slug: 'how-much-does-couch-cleaning-cost-utah',
    title: 'How Much Does Couch Cleaning Cost in Utah? (2026 Prices)',
    metaTitle: 'How Much Does Couch Cleaning Cost in Utah? 2026 Prices | LivinGreen',
    excerpt: 'A clear breakdown of what professional couch and upholstery cleaning costs in Utah County and Salt Lake, by sofa size and type.',
    date: '2026-06-20',
    image: '/images/gallery/gallery-3.jpg',
    readTime: '4 min read',
    keywords: ['couch cleaning cost', 'upholstery cleaning prices utah', 'sofa cleaning cost'],
    body: [
      { type: 'p', text: 'If you are searching for couch cleaning near you in Utah, the first thing you want to know is the price. The good news is that professional upholstery cleaning is affordable, and it costs far less than replacing a sofa that just needs a deep clean.' },
      { type: 'h2', text: 'Average couch cleaning prices' },
      { type: 'p', text: 'At LivinGreen, our upholstery cleaning prices are simple and based on the size of the piece:' },
      { type: 'ul', items: ['Single seat sofa: starting at $35', 'Two seat loveseat: around $65', 'Three seat sofa: around $85', 'Sectionals: from $100 depending on size', 'Dining chairs: $10 to $20 each'] },
      { type: 'p', text: 'Tough pet stains or heavy odor treatment may add a little, and we always tell you the full price before we start. Every quote is free and there is no obligation.' },
      { type: 'h2', text: 'What changes the price?' },
      { type: 'p', text: 'Three things mostly affect the cost: the size of your furniture, the fabric type, and how heavy the stains or odors are. A small armchair is quick, while a large sectional with pet stains takes more time and product.' },
      { type: 'h2', text: 'Is it worth it?' },
      { type: 'p', text: 'A quality sofa costs hundreds or thousands of dollars to replace. A professional cleaning brings it back to life for a fraction of that, removes allergens and odors, and makes your living room feel new again. We also offer fabric protection to keep it cleaner for longer.' },
      { type: 'p', text: 'Ready for a fresh couch? Get a free quote for upholstery and couch cleaning anywhere in Utah County and Salt Lake County.' },
    ],
  },
  {
    slug: 'remove-pet-stains-odors-couch',
    title: 'How to Remove Pet Stains and Odors From Your Couch',
    metaTitle: 'How to Remove Pet Stains and Odors From a Couch | LivinGreen Utah',
    excerpt: 'Practical steps to treat pet stains and smells on upholstery, and when it is time to call a professional.',
    date: '2026-06-13',
    image: '/images/gallery/gallery-11.jpg',
    readTime: '4 min read',
    keywords: ['pet stain removal couch', 'pet odor removal upholstery', 'dog urine sofa'],
    body: [
      { type: 'p', text: 'Pets are family, but pet accidents on the couch are no fun. The key with pet stains and odors is to act fast and to treat the smell at the source, not just the surface.' },
      { type: 'h2', text: 'Act quickly' },
      { type: 'p', text: 'Blot the spot with a clean cloth as soon as you can. Press down to soak up as much liquid as possible. Do not rub, because rubbing pushes the stain deeper into the fibers.' },
      { type: 'h2', text: 'A simple home treatment' },
      { type: 'ul', items: ['Mix equal parts water and white vinegar', 'Lightly dab the area, do not soak it', 'Blot again with a dry cloth', 'Let it air dry and check the fabric care tag first'] },
      { type: 'h2', text: 'Why odors come back' },
      { type: 'p', text: 'Pet urine soaks through the fabric into the cushion and padding underneath. Home cleaning often treats only the top layer, so the smell returns days later. A professional deep clean with hot water extraction reaches the deeper layers and neutralizes the odor at its source.' },
      { type: 'h2', text: 'When to call a pro' },
      { type: 'p', text: 'If the stain is large, old, or the smell keeps coming back, it is time for professional pet stain and odor removal. We serve homes across Utah County and Salt Lake County and can usually have your couch fresh and dry the same day.' },
    ],
  },
  {
    slug: 'microfiber-vs-fabric-vs-leather-couch-cleaning',
    title: 'Microfiber, Fabric, or Leather: How Each Couch Is Cleaned',
    metaTitle: 'Microfiber vs Fabric vs Leather Couch Cleaning | LivinGreen',
    excerpt: 'Different couch materials need different care. Here is how each type should be cleaned to look its best without damage.',
    date: '2026-06-06',
    image: '/images/gallery/gallery-16.jpg',
    readTime: '3 min read',
    keywords: ['microfiber couch cleaning', 'leather sofa cleaning', 'fabric couch cleaning'],
    body: [
      { type: 'p', text: 'Not every couch is cleaned the same way. Using the wrong method or product can leave marks, water rings, or even damage the material. Here is a quick guide to the three most common types.' },
      { type: 'h2', text: 'Microfiber' },
      { type: 'p', text: 'Microfiber is soft and popular with families, but it shows water marks easily. It needs the right amount of moisture and even drying. Professional extraction lifts the dirt without leaving rings behind.' },
      { type: 'h2', text: 'Fabric and woven upholstery' },
      { type: 'p', text: 'Most fabric sofas respond very well to hot water extraction, which flushes out dirt, allergens and stains and then pulls the moisture back out so the couch dries fast. This is our specialty.' },
      { type: 'h2', text: 'Leather' },
      { type: 'p', text: 'Leather is not cleaned with water extraction. It needs gentle cleaning and conditioning so it stays soft and does not crack. Always check what your couch is made of before treating it.' },
      { type: 'p', text: 'Not sure what your couch is made of? No problem. We identify the material and use the safe method for it. Get a free quote for couch cleaning in your city.' },
    ],
  },
  {
    slug: 'how-often-clean-upholstery',
    title: 'How Often Should You Clean Your Upholstery?',
    metaTitle: 'How Often Should You Clean Your Couch and Upholstery? | LivinGreen',
    excerpt: 'A simple guide to how often sofas, chairs and mattresses should be professionally cleaned to stay fresh and healthy.',
    date: '2026-05-30',
    image: '/images/gallery/gallery-20.jpg',
    readTime: '3 min read',
    keywords: ['how often clean couch', 'upholstery cleaning frequency', 'sofa cleaning schedule'],
    body: [
      { type: 'p', text: 'Your couch quietly collects dust, skin cells, food crumbs, pet hair and allergens every single day. Cleaning it on a regular schedule keeps your home healthier and your furniture looking new for years longer.' },
      { type: 'h2', text: 'A good rule of thumb' },
      { type: 'ul', items: ['Most households: every 12 months', 'Homes with kids or pets: every 6 months', 'Allergy sufferers: every 4 to 6 months', 'High use furniture: twice a year'] },
      { type: 'h2', text: 'Signs it is overdue' },
      { type: 'p', text: 'If your couch has a faint odor, visible dingy spots, or you notice more sneezing at home, it is time for a deep clean. Fabric protection applied after cleaning helps stretch the time between visits.' },
      { type: 'p', text: 'We make it easy with at home service across Utah County and Salt Lake County. Book a cleaning and keep your furniture fresh all year.' },
    ],
  },
  {
    slug: 'what-is-fabric-protection-worth-it',
    title: 'What Is Fabric Protection and Is It Worth It?',
    metaTitle: 'What Is Fabric Protection and Is It Worth It? | LivinGreen Utah',
    excerpt: 'Fabric protection keeps spills from soaking in. Here is how it works and whether it is worth adding to your couch.',
    date: '2026-05-23',
    image: '/images/services/protection.webp',
    readTime: '3 min read',
    keywords: ['fabric protection', 'scotchgard couch', 'stain protection worth it'],
    body: [
      { type: 'p', text: 'You have probably heard of fabric protection or stain protection when getting a couch cleaned. So what is it really, and is it worth the extra cost?' },
      { type: 'h2', text: 'How it works' },
      { type: 'p', text: 'Fabric protection puts an invisible barrier around each fiber of your couch. When a spill happens, the liquid beads up on the surface instead of soaking in, which gives you time to wipe it away before it becomes a stain.' },
      { type: 'h2', text: 'The benefits' },
      { type: 'ul', items: ['Spills wipe up instead of soaking in', 'Your couch stays cleaner between deep cleans', 'Less wear and fading over time', 'Easier day to day cleanup'] },
      { type: 'h2', text: 'Is it worth it?' },
      { type: 'p', text: 'For families with kids or pets, fabric protection is absolutely worth it. It is most effective when applied right after a professional cleaning, on fresh clean fibers. It needs to be reapplied after each deep clean to stay effective.' },
      { type: 'p', text: 'We add fabric and stain protection to any upholstery cleaning. Ask for it when you book your free quote.' },
    ],
  },
  {
    slug: '5-signs-sofa-needs-professional-cleaning',
    title: '5 Signs Your Sofa Needs a Professional Cleaning',
    metaTitle: '5 Signs Your Sofa Needs Professional Cleaning | LivinGreen',
    excerpt: 'Not sure if your couch needs a deep clean? Here are five clear signs it is time to call in the pros.',
    date: '2026-05-16',
    image: '/images/gallery/gallery-12.jpg',
    readTime: '3 min read',
    keywords: ['sofa needs cleaning', 'when to clean couch', 'professional upholstery cleaning'],
    body: [
      { type: 'p', text: 'Couches hide a lot of dirt before they actually look dirty. Here are five signs it is time for a professional upholstery cleaning.' },
      { type: 'h2', text: '1. There is a faint odor' },
      { type: 'p', text: 'If your couch smells a little musty or holds onto pet and food smells, deep cleaning removes the odor at the source.' },
      { type: 'h2', text: '2. The color looks dull' },
      { type: 'p', text: 'A buildup of body oils and dust slowly dulls the fabric. A deep clean often brings back the original color.' },
      { type: 'h2', text: '3. Allergies feel worse at home' },
      { type: 'p', text: 'Sofas trap dust mites and allergens. If you sneeze more on the couch, it needs a clean.' },
      { type: 'h2', text: '4. Visible stains or spots' },
      { type: 'p', text: 'Spills, pet accidents and marks that will not wipe away need professional treatment to remove fully.' },
      { type: 'h2', text: '5. It has been over a year' },
      { type: 'p', text: 'If you cannot remember the last time it was cleaned, it is overdue. Book a free quote and we will bring it back to life.' },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  // QUEUED ARTICLES — future-dated. Each appears automatically on its date when
  // the weekly Vercel cron rebuilds the site. One new article goes live each week.
  // ───────────────────────────────────────────────────────────────────────────
  {
    slug: 'how-to-remove-coffee-wine-stains-from-couch',
    title: 'How to Remove Coffee, Wine and Ink Stains From a Couch',
    metaTitle: 'How to Remove Coffee, Wine & Ink Stains From a Couch | LivinGreen',
    excerpt: 'Quick first steps for the three most common couch stains, and when a stain needs a professional.',
    date: '2026-06-29',
    image: '/images/gallery/gallery-11.jpg',
    readTime: '4 min read',
    keywords: ['remove coffee stain couch', 'wine stain sofa', 'ink stain upholstery'],
    body: [
      { type: 'p', text: 'Spills happen. With the three most common couch stains, the trick is to act fast and blot, never rub. Here is what to do for each.' },
      { type: 'h2', text: 'Coffee' },
      { type: 'p', text: 'Blot up as much as you can with a dry cloth. Mix a little dish soap with cool water, dab gently, then blot dry. Avoid hot water, which can set the stain.' },
      { type: 'h2', text: 'Red wine' },
      { type: 'p', text: 'Blot immediately. Sprinkle a little salt to absorb the liquid, then dab with cool water. Do not scrub, which spreads the color deeper into the fibers.' },
      { type: 'h2', text: 'Ink' },
      { type: 'p', text: 'Ink is the toughest. Dab very lightly with a tiny amount of rubbing alcohol on a white cloth and blot. Test a hidden spot first, and stop if color transfers.' },
      { type: 'h2', text: 'When to call a pro' },
      { type: 'p', text: 'If the stain is large, old, or does not lift after a gentle attempt, stop before you set it. Our professional treatment removes most stains safely without damaging the fabric.' },
    ],
  },
  {
    slug: 'professional-vs-diy-couch-cleaning',
    title: 'Professional vs DIY Couch Cleaning: What Is Worth It?',
    metaTitle: 'Professional vs DIY Couch Cleaning: What Is Worth It? | LivinGreen',
    excerpt: 'When a rental machine or home spray is enough, and when professional cleaning actually saves you money.',
    date: '2026-07-06',
    image: '/images/gallery/gallery-12.jpg',
    readTime: '3 min read',
    keywords: ['diy couch cleaning', 'professional upholstery cleaning worth it'],
    body: [
      { type: 'p', text: 'You can clean a couch yourself, but it is not always the best choice. Here is an honest look at when DIY works and when a professional is worth it.' },
      { type: 'h2', text: 'When DIY is fine' },
      { type: 'p', text: 'A small fresh spill, light dust, or a quick freshen-up before guests. A vacuum and a gentle fabric-safe spray handle these well.' },
      { type: 'h2', text: 'When a professional pays off' },
      { type: 'ul', items: ['Set-in stains or pet odors', 'Allergies or asthma in the home', 'A large sectional or delicate fabric', 'Furniture you want to last many more years'] },
      { type: 'h2', text: 'The hidden risk of DIY' },
      { type: 'p', text: 'Over-wetting is the most common mistake. Too much water leaves rings, takes days to dry, and can grow mildew inside the cushion. Professional extraction pulls the moisture back out, so it dries in hours.' },
      { type: 'p', text: 'Not sure which your couch needs? Get a free quote and we will give you an honest answer.' },
    ],
  },
  {
    slug: 'how-to-get-pet-smell-out-of-couch',
    title: 'How to Get the Pet Smell Out of Your Couch for Good',
    metaTitle: 'How to Get Pet Smell Out of a Couch for Good | LivinGreen Utah',
    excerpt: 'Why pet odors keep coming back, and the only way to remove them at the source.',
    date: '2026-07-13',
    image: '/images/gallery/gallery-16.jpg',
    readTime: '3 min read',
    keywords: ['pet smell couch', 'dog smell sofa', 'pet odor removal upholstery'],
    body: [
      { type: 'p', text: 'You love your dog, but not the smell it leaves on the couch. If the odor keeps returning no matter what you spray, here is why and what actually works.' },
      { type: 'h2', text: 'Why the smell comes back' },
      { type: 'p', text: 'Pet oils and accidents soak past the fabric into the cushion and padding. Sprays only mask the top layer, so the smell returns within days as it rises back up.' },
      { type: 'h2', text: 'What actually removes it' },
      { type: 'p', text: 'The odor has to be neutralized at the source, deep in the fibers and padding. Hot water extraction flushes it out instead of covering it, which is why the result lasts.' },
      { type: 'h2', text: 'Keeping it fresh' },
      { type: 'p', text: 'After cleaning, fabric protection makes future accidents easier to wipe up before they soak in. For homes with pets, a deep clean every six months keeps things fresh.' },
      { type: 'p', text: 'Tired of the pet smell? Book a free quote and we will get rid of it at the source.' },
    ],
  },
  {
    slug: 'how-to-care-for-different-couch-fabrics',
    title: 'How to Care for Different Couch Fabrics',
    metaTitle: 'How to Care for Microfiber, Linen, Velvet & Leather Couches | LivinGreen',
    excerpt: 'A simple care guide for the most common couch fabrics so you do not accidentally ruin yours.',
    date: '2026-07-20',
    image: '/images/gallery/gallery-18.jpg',
    readTime: '4 min read',
    keywords: ['couch fabric care', 'microfiber care', 'velvet couch cleaning', 'linen sofa'],
    body: [
      { type: 'p', text: 'Different couch fabrics need different care. Using the wrong method is the fastest way to leave a water ring or damage the material. Here is a quick guide.' },
      { type: 'h2', text: 'Microfiber' },
      { type: 'p', text: 'Durable but shows water marks. Vacuum often and blot spills right away. Use minimal moisture so it dries evenly.' },
      { type: 'h2', text: 'Linen and cotton' },
      { type: 'p', text: 'Breathable but prone to shrinking and water stains. These respond well to professional extraction but are easy to over-wet at home.' },
      { type: 'h2', text: 'Velvet' },
      { type: 'p', text: 'Beautiful but delicate. Brush in the direction of the pile and never scrub. Velvet usually needs a professional to avoid crushing the nap.' },
      { type: 'h2', text: 'Leather' },
      { type: 'p', text: 'Never use water extraction. Leather needs gentle cleaning and conditioning so it stays soft and does not crack.' },
      { type: 'p', text: 'Not sure what your couch is made of? We identify the fabric and use the safe method for it. Get a free quote today.' },
    ],
  },
  {
    slug: 'what-to-expect-couch-cleaning-appointment',
    title: 'What to Expect During a Couch Cleaning Appointment',
    metaTitle: 'What to Expect During a Couch Cleaning Appointment | LivinGreen',
    excerpt: 'A step-by-step of how an at-home upholstery cleaning works, how long it takes, and how to prepare.',
    date: '2026-07-27',
    image: '/images/gallery/gallery-20.jpg',
    readTime: '3 min read',
    keywords: ['couch cleaning appointment', 'what to expect upholstery cleaning'],
    body: [
      { type: 'p', text: 'Booking your first professional couch cleaning? Here is exactly what happens so there are no surprises.' },
      { type: 'h2', text: 'Before we arrive' },
      { type: 'p', text: 'Just clear small items off the couch and give us a clear path to it. We bring everything else and only need access to an electrical outlet.' },
      { type: 'h2', text: 'The cleaning' },
      { type: 'ul', items: ['We inspect the fabric and identify any stains', 'Deep vacuum to lift loose dirt and pet hair', 'Pre-treat stains and high-use areas', 'Hot water extraction to flush out the rest', 'Optional fabric protection to finish'] },
      { type: 'h2', text: 'How long and drying' },
      { type: 'p', text: 'Most couches take 30 to 60 minutes. Thanks to low-moisture extraction, they are usually dry in 4 to 6 hours, so you can use the room the same day.' },
      { type: 'p', text: 'Ready to book? Get a free quote and pick a time that works for you.' },
    ],
  },
  {
    slug: 'extend-the-life-of-your-sofa',
    title: 'How to Extend the Life of Your Sofa',
    metaTitle: 'How to Extend the Life of Your Sofa | LivinGreen Utah',
    excerpt: 'Simple habits that keep a couch comfortable and good-looking for years longer.',
    date: '2026-08-03',
    image: '/images/gallery/gallery-24.jpg',
    readTime: '3 min read',
    keywords: ['extend sofa life', 'make couch last longer', 'sofa maintenance'],
    body: [
      { type: 'p', text: 'A good sofa is an investment. With a few easy habits, you can keep it comfortable and looking great for many more years.' },
      { type: 'h2', text: 'Vacuum weekly' },
      { type: 'p', text: 'Dust and crumbs act like sandpaper inside the fibers. A quick weekly vacuum prevents that slow wear and keeps the fabric fresh.' },
      { type: 'h2', text: 'Rotate and fluff cushions' },
      { type: 'p', text: 'Rotating cushions spreads out the wear so one spot does not sag first. Fluffing keeps them full and comfortable.' },
      { type: 'h2', text: 'Treat spills immediately' },
      { type: 'p', text: 'Blot right away. The longer a spill sits, the deeper it sets. Fabric protection buys you precious extra minutes.' },
      { type: 'h2', text: 'Deep clean once or twice a year' },
      { type: 'p', text: 'A professional clean removes the buildup a vacuum cannot reach, restoring color and freshness. Book a free quote to keep yours like new.' },
    ],
  },
  {
    slug: 'allergies-and-your-upholstery',
    title: 'Allergies and Your Upholstery: What You Should Know',
    metaTitle: 'Allergies and Your Upholstery: What You Should Know | LivinGreen',
    excerpt: 'How couches and mattresses trap allergens, and how a deep clean helps you breathe easier at home.',
    date: '2026-08-10',
    image: '/images/gallery/gallery-3.jpg',
    readTime: '3 min read',
    keywords: ['upholstery allergens', 'couch dust mites', 'allergy furniture cleaning'],
    body: [
      { type: 'p', text: 'If your allergies feel worse at home than outside, your furniture may be part of the problem. Here is what to know.' },
      { type: 'h2', text: 'What couches trap' },
      { type: 'p', text: 'Sofas and mattresses collect dust mites, pet dander, pollen and skin cells deep in the fibers. Every time you sit down, some of it puffs back into the air you breathe.' },
      { type: 'h2', text: 'Why vacuuming is not enough' },
      { type: 'p', text: 'A vacuum only reaches the surface. Dust mites and allergens live deeper, where regular cleaning cannot remove them.' },
      { type: 'h2', text: 'How a deep clean helps' },
      { type: 'p', text: 'Hot water extraction flushes allergens out of the deep fibers, which can noticeably reduce sneezing and congestion at home. For allergy sufferers, every 4 to 6 months is ideal.' },
      { type: 'p', text: 'Breathe easier at home. Book a free quote for upholstery and mattress cleaning today.' },
    ],
  },
  {
    slug: 'spring-cleaning-your-furniture-utah',
    title: 'Spring Cleaning Your Furniture in Utah: A Checklist',
    metaTitle: 'Spring Cleaning Your Furniture in Utah: A Checklist | LivinGreen',
    excerpt: 'A simple seasonal checklist to refresh your couches, mattresses and carpets after a long Utah winter.',
    date: '2026-08-17',
    image: '/images/gallery/gallery-28.jpg',
    readTime: '3 min read',
    keywords: ['spring cleaning furniture', 'seasonal upholstery cleaning utah'],
    body: [
      { type: 'p', text: 'After a long Utah winter of closed windows and indoor living, your furniture has collected a season of dust and allergens. Here is a simple refresh checklist.' },
      { type: 'h2', text: 'The furniture checklist' },
      { type: 'ul', items: ['Vacuum every couch, chair and mattress', 'Spot-treat any stains before they set further', 'Deep clean upholstery that sees daily use', 'Add fabric protection before spill season', 'Refresh area rugs and high-traffic carpet'] },
      { type: 'h2', text: 'Why spring is the right time' },
      { type: 'p', text: 'Cleaning now clears out the winter buildup of dust and allergens, and protected fabric is ready for summer guests, open windows and busier days.' },
      { type: 'p', text: 'Make it easy. Book a free quote and we will handle the deep cleaning while you enjoy the spring.' },
    ],
  },
];
